### ISSUE TITLE
Add your first project

### ISSUE THREAD

**Issue by lovy003** [lovy003/First-PR#2]
Add your particular language folder or if it already exists then add your projects into it.

**Comment by ashusharma-cs** [comment]
Do you want only a folder?

**Comment by Noburu-Hasashi** [comment]
I can make a project in python, and I'm willing to participate for hacktoberfest. Tell me what project do you want me to make

**Comment by GuptaHimanshu01** [comment]
Hey, I would like to contribute to this repo. Please assign me this issue.

**Comment by lovy003** [comment]
Everyone can contribute guys just make a folder of your language and put your project in it and open a PR :)

**Comment by aishapervin** [comment]
@lovy003 plz close this issue and create a new issue if you want because i guess if multiple people create and merge pr's in same issue,it becomes an excluded project in hacktoberfest.

**Comment by isha614** [comment]
I want to add my small project in JavaScript folder. Please assign  it.

**Comment by Gourav-s12** [comment]
i would like to contribute in this issue

**Comment by Gourav-s12** [comment]
please review PR #32 and marge . Thank you

**Comment by nilupulmanodya** [comment]
Hey,  Please review PR #33, hope It is acceptable PR. Thank you.

**Comment by lovy003** [comment]
> 
> 
> I want to add my small project in JavaScript folder. Please assign it.

yes you can add

**Comment by isha614** [comment]
> > I want to add my small project in JavaScript folder. Please assign it.
> 
> yes you can add

without assigning if I add will it be counted to successful PR to Hacktoberfest?

**Comment by humorouswarrior** [comment]
Hey! May I pls add one of my projects here?

**Comment by lovy003** [comment]
> 
> 
> > > I want to add my small project in JavaScript folder. Please assign it.
> > 
> > 
> > yes you can add
> 
> without assigning if I add will it be counted to successful PR to Hacktoberfest?

yes

**Comment by Sameer1408** [comment]
sir I have added my js project pls have a look  #47

**Comment by amarjeetsinha** [comment]
Just added a PR, kindly verify and merge it to this repo.

**Comment by KartikKode** [comment]
I have design of styled cards can I add it.
